# GitHub Action that uses the Black tool to check PEP-8 format an a repo pull request.
# If all Python code in the pull request is compliant with Black then this Action does nothing.
# Othewrwise, a warning message is issued

# (Action)  Workflow is entire file
name: check-PEP8-format
# The name of the (Action) workflow file (optional)
on: [pull_request]
# GitHub event [pull_request] that triggers the workflow. (required)
# The available events
# ref: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#in-this-article
jobs:
# start jobs in workflow. In this case one job named check-PEP8-format
  check-PEP8-format:
    runs-on: ubuntu-latest
    steps:
#steps in job
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
      - name: If needed, black fails
        if: failure()
        run: |
          echo "files not PEP-8 fornat compliant"